name: test

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: npm-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}
            ${{ runner.os }}-node

      - name: install
        run: npm ci

      - uses: willcaul/jest-github-action@v1.0.0
        if: github.actor!='dependabot[bot]'
        with:
          test-command: npm run test:ci:coverage
          coverage-comment: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
